#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

APP_NAME="great-galguti-server-deploy"
SUBSCRIPTION_ID="a7a998e4-0086-42a6-84b1-1f13aa768ce6"
RESOURCE_GROUP="great-galguti-dev-rg"
CONTAINER_APP="great-galguti-server"
REPO="hgrosche95/great_galguti_game"
FIC_NAME="github-actions-main"
ENV_FILE="scripts/.setup-azure-deploy-oidc.env"

banner "Azure OIDC fuer automatisches Server-Deployment"

# ── Stage 1: Voraussetzungen ───────────────────────────────────────────────
stage "Voraussetzungen pruefen"
say "Wir richten OIDC (Federated Credentials) fuer die neue GitHub-Actions-Pipeline ein."
say "Vorteil gegenueber einem klassischen Service-Principal-Secret: Azure vertraut"
say "GitHub-Tokens fuer genau diesen Branch, es gibt kein langlebiges Passwort,"
say "das irgendwo geleakt oder rotiert werden muss."
echo

if ! command -v az >/dev/null 2>&1; then
  warn "az CLI nicht gefunden. Bitte zuerst installieren: https://aka.ms/installazurecliwindows"
  exit 1
fi

CURRENT_SUB=$(az account show --query id -o tsv 2>/dev/null || true)
if [[ -z "$CURRENT_SUB" ]]; then
  warn "Nicht bei az CLI eingeloggt."
  confirm "Jetzt 'az login' starten?" || { warn "Abgebrochen."; exit 1; }
  az login >/dev/null
  CURRENT_SUB=$(az account show --query id -o tsv)
fi

if [[ "$CURRENT_SUB" != "$SUBSCRIPTION_ID" ]]; then
  warn "Aktive Subscription ($CURRENT_SUB) weicht von der erwarteten ($SUBSCRIPTION_ID) ab."
  confirm "Trotzdem mit der aktiven Subscription ($CURRENT_SUB) fortfahren?" || {
    warn "Wechsle mit 'az account set --subscription $SUBSCRIPTION_ID' und starte neu."
    exit 1
  }
  SUBSCRIPTION_ID="$CURRENT_SUB"
else
  say "Richtige Subscription aktiv: $SUBSCRIPTION_ID"
fi
pause

# ── Stage 2: App-Registrierung + Service Principal ────────────────────────
stage "Azure-AD-App-Registrierung + Service Principal"
say "Das ist die Identitaet, als die sich GitHub Actions spaeter bei Azure anmeldet -"
say "vergleichbar mit einem eigenen Benutzerkonto, aber nur fuer diese eine Pipeline."

AZURE_CLIENT_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv 2>/dev/null || true)
if [[ -n "$AZURE_CLIENT_ID" ]]; then
  note "App-Registrierung '$APP_NAME' existiert schon (appId: $AZURE_CLIENT_ID) - wiederverwenden."
else
  confirm "Jetzt 'az ad app create --display-name $APP_NAME' ausfuehren?" || { warn "Abgebrochen."; exit 1; }
  AZURE_CLIENT_ID=$(az ad app create --display-name "$APP_NAME" --query appId -o tsv)
  say "App-Registrierung angelegt: $AZURE_CLIENT_ID"
fi

if az ad sp show --id "$AZURE_CLIENT_ID" >/dev/null 2>&1; then
  note "Service Principal existiert schon."
else
  az ad sp create --id "$AZURE_CLIENT_ID" >/dev/null
  say "Service Principal angelegt."
fi

write_env AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
pause

# ── Stage 3: Rolle zuweisen (least privilege) ──────────────────────────────
stage "Rolle zuweisen — nur auf die Resource Group, nicht die ganze Subscription"
say "Die Pipeline soll ausschliesslich 'great-galguti-server' in '$RESOURCE_GROUP' aktualisieren"
say "duerfen - deshalb 'Container Apps Contributor', gescoped auf genau diese Resource Group,"
say "statt 'Contributor' auf der gesamten Subscription."

SCOPE="/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}"
EXISTING_ROLE=$(az role assignment list --assignee "$AZURE_CLIENT_ID" --scope "$SCOPE" \
  --query "[?roleDefinitionName=='Container Apps Contributor'] | [0].id" -o tsv 2>/dev/null || true)

if [[ -n "$EXISTING_ROLE" ]]; then
  note "Rolle ist schon zugewiesen."
else
  confirm "Rolle 'Container Apps Contributor' auf '$RESOURCE_GROUP' zuweisen?" || { warn "Abgebrochen."; exit 1; }
  az role assignment create --assignee "$AZURE_CLIENT_ID" --role "Container Apps Contributor" --scope "$SCOPE" >/dev/null
  say "Rolle zugewiesen."
fi
pause

# ── Stage 4: Federated Credential fuer GitHub Actions ──────────────────────
stage "Federated Credential — GitHub Actions darf sich als diese App ausweisen"
say "Das verknuepft die App-Registrierung mit genau diesem Repo + Branch: nur ein"
say "GitHub-Actions-Workflow, der auf dem 'main'-Branch von $REPO laeuft, bekommt ein"
say "Token, das Azure akzeptiert - kein anderer Branch, kein fremdes Repo."

EXISTING_FIC=$(az ad app federated-credential list --id "$AZURE_CLIENT_ID" \
  --query "[?name=='$FIC_NAME'] | [0].name" -o tsv 2>/dev/null || true)

if [[ -n "$EXISTING_FIC" ]]; then
  note "Federated Credential '$FIC_NAME' existiert schon."
else
  confirm "Federated Credential fuer $REPO (main-Branch) anlegen?" || { warn "Abgebrochen."; exit 1; }
  az ad app federated-credential create --id "$AZURE_CLIENT_ID" --parameters "{
    \"name\": \"$FIC_NAME\",
    \"issuer\": \"https://token.actions.githubusercontent.com\",
    \"subject\": \"repo:${REPO}:ref:refs/heads/main\",
    \"audiences\": [\"api://AzureADTokenExchange\"]
  }" >/dev/null
  say "Federated Credential angelegt."
fi
pause

# ── Stage 5: gh Login + GitHub Secrets setzen ──────────────────────────────
stage "GitHub Secrets setzen"
say "Der Workflow (.github/workflows/azure-container-apps.yml) liest drei Secrets:"
say "AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID. Die setzen wir jetzt im Repo."

if ! command -v gh >/dev/null 2>&1; then
  warn "gh CLI nicht gefunden. Secrets muessen manuell im Browser gesetzt werden:"
  note "https://github.com/${REPO}/settings/secrets/actions"
elif ! gh auth status >/dev/null 2>&1; then
  say "Noch nicht bei gh eingeloggt."
  confirm "Jetzt 'gh auth login' im Browser starten?" && gh auth login --web -h github.com || true
fi

TENANT_ID=$(az account show --query tenantId -o tsv)
write_env AZURE_TENANT_ID "$TENANT_ID"
write_env AZURE_SUBSCRIPTION_ID "$SUBSCRIPTION_ID"

set_secret AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
set_secret AZURE_TENANT_ID "$TENANT_ID"
set_secret AZURE_SUBSCRIPTION_ID "$SUBSCRIPTION_ID"
pause

# ── Stage 6: PR mergen ──────────────────────────────────────────────────────
stage "Workflow aktivieren"
say "Der fertige Workflow liegt auf dem Branch 'ci/server-auto-deploy'. Damit er beim"
say "naechsten Push auf 'main' greift, muss der Pull Request noch gemerged werden."
open_url "https://github.com/${REPO}/pull/new/ci/server-auto-deploy"
step "PR erstellen (falls noch nicht geschehen) und mergen."
pause "Gemerged? Enter zum Abschliessen."

finish
say "Ab jetzt deployed jeder Push auf main mit Aenderungen in server/ oder src/ automatisch."
