#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# Git Bash/MSYS auf Windows wandelt Argumente, die mit "/" beginnen (wie
# "/subscriptions/..."), sonst faelschlicherweise in Windows-Dateipfade um,
# bevor sie an az/gh uebergeben werden. Auf Linux/macOS ist das ein No-op.
export MSYS_NO_PATHCONV=1

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

SUBSCRIPTION_ID="a7a998e4-0086-42a6-84b1-1f13aa768ce6"
RESOURCE_GROUP="great-galguti-dev-rg"
CONTAINER_APP="great-galguti-server"
PG_SERVER_NAME="great-galguti-dev-psql"
PG_LOCATION="swedencentral"
PG_DB_NAME="galguti"
PG_ADMIN_USER="galguti_admin"
ENV_FILE="scripts/.setup-azure-postgres.env"

banner "Azure Postgres fuer echte Nutzer-Persistenz"

# ── Stage 1: Voraussetzungen ───────────────────────────────────────────────
stage "Voraussetzungen pruefen"
say "Legt einen echten Postgres-Server in Azure an, damit Nutzerkonten einen"
say "Server-Neustart ueberleben (bisher In-Memory). Gleiche Konfiguration wie"
say "beim ai-trip-planer-Referenzprojekt: Burstable B1ms, 32GB, Postgres 16."
say "Region bewusst '$PG_LOCATION' - andere Regionen waren bei diesem"
say "Subscription-Typ teils gesperrt, swedencentral hat beim Referenzprojekt"
say "funktioniert."
echo

if ! command -v az >/dev/null 2>&1; then
  warn "az CLI nicht gefunden. Bitte zuerst installieren: https://aka.ms/installazurecliwindows"
  exit 1
fi

CURRENT_SUB=$(az account show --query id -o tsv 2>/dev/null || true)
if [[ -z "$CURRENT_SUB" ]]; then
  warn "Nicht bei az CLI eingeloggt."
  confirm "Jetzt 'az login' starten?" || { warn "Abgebrochen."; exit 1; }
  az login >/dev/null
  CURRENT_SUB=$(az account show --query id -o tsv)
fi

if [[ "$CURRENT_SUB" != "$SUBSCRIPTION_ID" ]]; then
  warn "Aktive Subscription ($CURRENT_SUB) weicht von der erwarteten ($SUBSCRIPTION_ID) ab."
  confirm "Trotzdem mit der aktiven Subscription ($CURRENT_SUB) fortfahren?" || {
    warn "Wechsle mit 'az account set --subscription $SUBSCRIPTION_ID' und starte neu."
    exit 1
  }
  SUBSCRIPTION_ID="$CURRENT_SUB"
else
  say "Richtige Subscription aktiv: $SUBSCRIPTION_ID"
fi
pause

# ── Stage 2: Postgres Flexible Server ──────────────────────────────────────
stage "Postgres Flexible Server anlegen"
say "Azure verwaltet damit Patching/Backups selbst. Burstable ist der"
say "guenstigste Tier - passend fuer ein Lernprojekt mit wenig Last."

EXISTING_SERVER=$(az postgres flexible-server show \
  --resource-group "$RESOURCE_GROUP" --name "$PG_SERVER_NAME" \
  --query name -o tsv 2>/dev/null || true)

PG_ADMIN_PASSWORD=$(_existing PG_ADMIN_PASSWORD || true)

if [[ -n "$EXISTING_SERVER" ]]; then
  note "Server '$PG_SERVER_NAME' existiert schon - wiederverwenden."
  if [[ -z "$PG_ADMIN_PASSWORD" ]]; then
    warn "Kein gespeichertes Passwort fuer den existierenden Server gefunden."
    ask_secret PG_ADMIN_PASSWORD "Admin-Passwort fuer '$PG_SERVER_NAME' eingeben:"
  fi
else
  confirm "Jetzt Postgres-Server '$PG_SERVER_NAME' anlegen (dauert einige Minuten)?" || { warn "Abgebrochen."; exit 1; }
  PG_ADMIN_PASSWORD=$(openssl rand -base64 24)
  write_env PG_ADMIN_PASSWORD "$PG_ADMIN_PASSWORD"

  az postgres flexible-server create \
    --resource-group "$RESOURCE_GROUP" \
    --name "$PG_SERVER_NAME" \
    --location "$PG_LOCATION" \
    --admin-user "$PG_ADMIN_USER" \
    --admin-password "$PG_ADMIN_PASSWORD" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --storage-size 32 \
    --version 16 \
    --public-access Enabled \
    --yes >/dev/null
  say "Server angelegt."
fi

EXISTING_DB=$(az postgres flexible-server db show \
  --resource-group "$RESOURCE_GROUP" --server-name "$PG_SERVER_NAME" \
  --name "$PG_DB_NAME" --query name -o tsv 2>/dev/null || true)

if [[ -n "$EXISTING_DB" ]]; then
  note "Datenbank '$PG_DB_NAME' existiert schon."
else
  az postgres flexible-server db create \
    --resource-group "$RESOURCE_GROUP" --server-name "$PG_SERVER_NAME" \
    --name "$PG_DB_NAME" >/dev/null
  say "Datenbank '$PG_DB_NAME' angelegt."
fi

EXISTING_FIREWALL=$(az postgres flexible-server firewall-rule show \
  --resource-group "$RESOURCE_GROUP" --server-name "$PG_SERVER_NAME" \
  --name AllowAllAzureServices --query name -o tsv 2>/dev/null || true)

if [[ -n "$EXISTING_FIREWALL" ]]; then
  note "Firewall-Regel fuer Azure-Dienste existiert schon."
else
  # 0.0.0.0-0.0.0.0 ist eine von Azure reservierte Sonder-Notation: erlaubt
  # Zugriffe von beliebigen Azure-internen Quell-IPs (unsere Container App),
  # NICHT das ganze Internet.
  az postgres flexible-server firewall-rule create \
    --resource-group "$RESOURCE_GROUP" --server-name "$PG_SERVER_NAME" \
    --name AllowAllAzureServices \
    --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 >/dev/null
  say "Firewall-Regel angelegt (erlaubt Azure-interne Zugriffe, nicht das offene Internet)."
fi

write_env PG_ADMIN_PASSWORD "$PG_ADMIN_PASSWORD"
pause

# ── Stage 3: Container App verbinden ───────────────────────────────────────
stage "DATABASE_URL an die Container App uebergeben"
say "Die Migrationen laufen beim Containerstart automatisch (siehe"
say "server/Dockerfile) - die App braucht dafuer nur die Verbindungs-URL als"
say "Umgebungsvariable, sonst nichts weiter."

PG_SERVER_FQDN=$(az postgres flexible-server show \
  --resource-group "$RESOURCE_GROUP" --name "$PG_SERVER_NAME" \
  --query fullyQualifiedDomainName -o tsv)

DATABASE_URL="postgresql://${PG_ADMIN_USER}:${PG_ADMIN_PASSWORD}@${PG_SERVER_FQDN}:5432/${PG_DB_NAME}?sslmode=require"

confirm "DATABASE_URL jetzt als Container-App-Secret setzen und die App neu starten?" || { warn "Abgebrochen."; exit 1; }

az containerapp secret set \
  --resource-group "$RESOURCE_GROUP" --name "$CONTAINER_APP" \
  --secrets database-url="$DATABASE_URL" >/dev/null

az containerapp update \
  --resource-group "$RESOURCE_GROUP" --name "$CONTAINER_APP" \
  --set-env-vars DATABASE_URL=secretref:database-url >/dev/null

say "Gesetzt. Die Container App startet gerade neu und wendet die Migration an."
note "Kurz pruefen: az containerapp logs show -n $CONTAINER_APP -g $RESOURCE_GROUP --tail 20"
pause

finish
say "Ab jetzt ueberleben Nutzerkonten einen Server-Neustart."
